server:
  port: 8181

spring:
  security:
    user:
      name: admin@email.com
      password: 123456

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    enabled: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    
    

aw:
  auth:
    provider-uri: "http://localhost:8081"
    # keytool -genkeypair -alias awblog -keyalg RSA -keypass 123456 -keystore awblog.jks -storepass 123456 -validity 3560
    # keytool -list -keystore awblog.jks
    jks:
      keypass: 123456
      storepass: 123456
      alias: awblog
      path: keystore/awblog.jks