
server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          default-label: main # master
          uri: https://github.com/wquintanilhadasilva/spring-cloud-lab # https://github.com/rafaelcam/delivery-configs # https://github.com/wquintanilhadasilva/spring-cloud-lab